# Generated by Django 5.1.4 on 2024-12-13 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netFitApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serie',
            name='treino',
        ),
        migrations.AddField(
            model_name='treino',
            name='series',
            field=models.ManyToManyField(related_name='treinos', to='netFitApp.serie'),
        ),
    ]
