# Generated by Django 5.1.4 on 2024-12-12 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netFitApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercicio',
            name='musculos',
            field=models.TextField(),
        ),
    ]
