# Generated by Django 5.1.4 on 2024-12-13 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netFitApp', '0002_alter_exercicio_musculos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entusiasta',
            name='nivel',
        ),
        migrations.RemoveField(
            model_name='entusiasta',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='especialidade',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='telefone',
        ),
        migrations.AddField(
            model_name='entusiasta',
            name='cpf',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='entusiasta',
            name='percentualDeGordura',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='entusiasta',
            name='personal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='netFitApp.personal'),
        ),
        migrations.AddField(
            model_name='entusiasta',
            name='peso',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='personal',
            name='cpf',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='personal',
            name='registroProfissional',
            field=models.TextField(null=True),
        ),
    ]
